name: "Hello World Workflow"


#Controls when the action will run. Triggers the workflow on push done to master or production branch
on:
  push:
    branches:
      - master
      - production


jobs:
  hello_world:
    runs-on: ubuntu_latest
    steps:
      - name: "Print Hello World"
        run:  echo "Hello world"
    
    

