name: "Multi Event Pipeline/Workflow" #name of the pipeline

on:
  push: #Event: whenever a push i smade to the repoistory on the master branch 
    branches:
        - master
        - Test
  
  pull_request: #Event: whenever a pull request is made to the repository
    branches:
        - master
    types:
        - closed
  
    


jobs:
  on-push: #job1-name
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps: #steps
        - name: "Running on master/test push"
          run: echo "Running on master/test push"


  on-pull-request: #job2 name
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
        - name: "Running on pull request"
          run: echo "Running on pull request"

  on-pull-request-closed: #job3
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
        - name: "Running on pull request closed"
          run: echo "Running on pull request closed"
